name: Publish to GHCR

on:
  push:
   branches:
     - main

jobs:
  ghcr: 
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repositories
        uses: actions/checkout@v4
        with:
          submodules: true
